
name: Test Checklist
description: A test issue template.
labels: ["test-checklist"]
type: checklist
projects: ["Defra-Data-Science-Centre-of-Excellence/137"]
assignees: ["SamRichDefra", "liza-wood-defra", "JackDale0", "tomkdefra"]

body:
  - type: dropdown
    id: fruits
    attributes:
      label: Select
      options:
        - Apple
        - Rambutan
        - Mango
    validations:
      required: false

  - type: checkboxes
    id: tasks
    attributes:
      label: Checklist
      options:
        - label: Task A
        - label: Task B
        - label: Task C
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Add any extra information here.
    validations:
      required: false
